"""Add checksum to recipes

Revision ID: 1a7daaa8fb4b
Revises: 8cd665380261
Create Date: 2025-12-27 21:17:07.934991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7daaa8fb4b'
down_revision: Union[str, Sequence[str], None] = '8cd665380261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('checksum', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'checksum')
    # ### end Alembic commands ###
