"""rename_proposed_to_draft

Revision ID: 20fdb31754ac
Revises: 9416b1c114e5
Create Date: 2026-01-18 15:32:28.335523

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '20fdb31754ac'
down_revision: Union[str, Sequence[str], None] = '9416b1c114e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE meals SET status = 'Draft' WHERE status = 'Proposed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE meals SET status = 'Proposed' WHERE status = 'Draft'")
    # ### end Alembic commands ###
