"""change scheduled_date from datetime to date

Revision ID: 35b0ad379e8c
Revises: bab71f5e8853
Create Date: 2026-02-16 20:19:00.685981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35b0ad379e8c"
down_revision: Union[str, Sequence[str], None] = "bab71f5e8853"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.alter_column(
            "scheduled_date",
            existing_type=sa.DATETIME(),
            type_=sa.Date(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.alter_column(
            "scheduled_date",
            existing_type=sa.Date(),
            type_=sa.DATETIME(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
