"""add household models and meal household_id

Revision ID: 4108b340e611
Revises: 35b0ad379e8c
Create Date: 2026-02-23 07:45:41.018768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4108b340e611"
down_revision: Union[str, Sequence[str], None] = "35b0ad379e8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("households", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_households_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_households_id"), ["id"], unique=False)

    op.create_table(
        "household_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "user_id", name="uq_household_user"),
    )
    with op.batch_alter_table("household_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_household_memberships_household_id"),
            ["household_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_household_memberships_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_household_memberships_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "household_template_exclusions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["meal_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "household_id", "template_id", name="uq_household_template"
        ),
    )
    with op.batch_alter_table("household_template_exclusions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_household_template_exclusions_household_id"),
            ["household_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_household_template_exclusions_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_household_template_exclusions_template_id"),
            ["template_id"],
            unique=False,
        )

    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("household_id", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_meals_household_id"), ["household_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_meals_household_id", "households", ["household_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.drop_constraint("fk_meals_household_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_meals_household_id"))
        batch_op.drop_column("household_id")

    with op.batch_alter_table("household_template_exclusions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_template_exclusions_template_id"))
        batch_op.drop_index(batch_op.f("ix_household_template_exclusions_id"))
        batch_op.drop_index(batch_op.f("ix_household_template_exclusions_household_id"))

    op.drop_table("household_template_exclusions")
    with op.batch_alter_table("household_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_household_memberships_id"))
        batch_op.drop_index(batch_op.f("ix_household_memberships_household_id"))

    op.drop_table("household_memberships")
    with op.batch_alter_table("households", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_households_id"))
        batch_op.drop_index(batch_op.f("ix_households_created_by"))

    op.drop_table("households")
    # ### end Alembic commands ###
