"""Add order to RecipeIngredient

Revision ID: 500b9e7565cc
Revises: addebffd449e
Create Date: 2026-01-01 21:21:07.218396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "500b9e7565cc"
down_revision: Union[str, Sequence[str], None] = "addebffd449e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredients",
        sa.Column("order", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe_ingredients", "order")
    # ### end Alembic commands ###
