"""Add preparation notes to recipe ingredients

Revision ID: 50114936ed77
Revises: 858f433f6607
Create Date: 2025-07-19 20:40:59.863170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50114936ed77'
down_revision: Union[str, Sequence[str], None] = '858f433f6607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'notes')
    # ### end Alembic commands ###
