"""Add protein field to recipes

Revision ID: 6c87feac5aaf
Revises: 500b9e7565cc
Create Date: 2026-01-03 22:00:11.955702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c87feac5aaf'
down_revision: Union[str, Sequence[str], None] = '500b9e7565cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('protein', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'protein')
    # ### end Alembic commands ###
