"""add suitable_for_diet

Revision ID: 7d68d01253c7
Revises: 6c87feac5aaf
Create Date: 2026-01-03 22:15:01.019576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d68d01253c7"
down_revision: Union[str, Sequence[str], None] = "6c87feac5aaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_diets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column(
            "diet_type",
            sa.Enum(
                "DIABETIC",
                "GLUTEN_FREE",
                "HALAL",
                "HINDU",
                "KOSHER",
                "LOW_CALORIE",
                "LOW_FAT",
                "LOW_LACTOSE",
                "LOW_SALT",
                "VEGAN",
                "VEGETARIAN",
                name="diettype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_diets_id"), "recipe_diets", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipe_diets_id"), table_name="recipe_diets")
    op.drop_table("recipe_diets")
    # ### end Alembic commands ###
