"""Initial migration

Revision ID: 7f3c4e8f01c1
Revises: e42718e24c6c
Create Date: 2025-12-27 11:41:39.719210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3c4e8f01c1'
down_revision: Union[str, Sequence[str], None] = 'e42718e24c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_components_id'), 'recipe_components', ['id'], unique=False)
    op.drop_table('recipe_tag')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.add_column('instructions', sa.Column('text', sa.Text(), nullable=False))
    op.alter_column('instructions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('instructions', 'recipe_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.drop_column('instructions', 'description')
    op.add_column('recipe_ingredients', sa.Column('component_id', sa.Uuid(), nullable=True))
    op.alter_column('recipe_ingredients', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'ingredient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'recipe_components', ['component_id'], ['id'])
    op.drop_column('recipe_ingredients', 'recipe_id')
    op.add_column('recipes', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('description_short', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('description_long', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('yield_amount', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('yield_unit', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=True))
    op.add_column('recipes', sa.Column('cuisine', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('category', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('active_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('total_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('serving_size', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('parent_recipe_id', sa.Uuid(), nullable=True))
    op.alter_column('recipes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('recipes', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.drop_column('recipes', 'description')
    op.drop_column('recipes', 'servings')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('recipes', sa.Column('servings', sa.INTEGER(), nullable=True))
    op.add_column('recipes', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.alter_column('recipes', 'owner_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recipes', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('recipes', 'parent_recipe_id')
    op.drop_column('recipes', 'version')
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipes', 'serving_size')
    op.drop_column('recipes', 'calories')
    op.drop_column('recipes', 'total_time_minutes')
    op.drop_column('recipes', 'active_time_minutes')
    op.drop_column('recipes', 'source_url')
    op.drop_column('recipes', 'category')
    op.drop_column('recipes', 'cuisine')
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'yield_unit')
    op.drop_column('recipes', 'yield_amount')
    op.drop_column('recipes', 'description_long')
    op.drop_column('recipes', 'description_short')
    op.drop_column('recipes', 'slug')
    op.add_column('recipe_ingredients', sa.Column('recipe_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'])
    op.alter_column('recipe_ingredients', 'ingredient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recipe_ingredients', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('recipe_ingredients', 'component_id')
    op.add_column('instructions', sa.Column('description', sa.TEXT(), nullable=False))
    op.alter_column('instructions', 'recipe_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('instructions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('instructions', 'text')
    op.alter_column('ingredients', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=1)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('recipe_tag',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.drop_index(op.f('ix_recipe_components_id'), table_name='recipe_components')
    op.drop_table('recipe_components')
    # ### end Alembic commands ###
