"""Implement normalized recipe model

Revision ID: 858f433f6607
Revises: 432a2a8dc5e5
Create Date: 2025-07-19 19:43:46.720237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '858f433f6607'
down_revision: Union[str, Sequence[str], None] = '432a2a8dc5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)

    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)

    op.add_column('recipes', sa.Column('name', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('prep_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.drop_index('ix_recipes_title', table_name='recipes')
    op.drop_column('recipes', 'title')
    op.drop_column('recipes', 'instructions')
    op.drop_column('recipes', 'ingredients')

    op.create_table('instructions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('step_number', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_instructions_id'), 'instructions', ['id'], unique=False)

    op.create_table('recipe_ingredients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=True),
                    sa.Column('ingredient_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('unit', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)

    op.create_table('recipe_tag',
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
                    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tag')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_instructions_id'), table_name='instructions')
    op.drop_table('instructions')
    op.add_column('recipes', sa.Column('ingredients', sa.TEXT(), nullable=False))
    op.add_column('recipes', sa.Column('instructions', sa.TEXT(), nullable=False))
    op.add_column('recipes', sa.Column('title', sa.VARCHAR(), nullable=False))
    op.create_index('ix_recipes_title', 'recipes', ['title'], unique=False)
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_column('recipes', 'source')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'cook_time_minutes')
    op.drop_column('recipes', 'prep_time_minutes')
    op.drop_column('recipes', 'name')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
