"""Add slots_checksum to meal_templates

Revision ID: 9416b1c114e5
Revises: 7a8148a48ef2
Create Date: 2026-01-16 21:18:01.386800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9416b1c114e5'
down_revision: Union[str, Sequence[str], None] = '7a8148a48ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots_checksum', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_meal_templates_slots_checksum'), ['slots_checksum'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_templates_slots_checksum'))
        batch_op.drop_column('slots_checksum')

    # ### end Alembic commands ###
