"""Change quantity to Float

Revision ID: addebffd449e
Revises: 6ab2c31fd460
Create Date: 2025-12-31 12:13:47.652944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "addebffd449e"
down_revision: Union[str, Sequence[str], None] = "6ab2c31fd460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredients", schema=None) as batch_op:
        batch_op.alter_column(
            "quantity",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Float(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredients", schema=None) as batch_op:
        batch_op.alter_column(
            "quantity",
            existing_type=sa.Float(),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
